version: '3.8'

services:
  moodle-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/docker-moodle-50/moodle:/var/www/html:delegated
      - /home/docker-moodle-50/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /mnt/moodledata:/var/moodledata:rw
    depends_on:
      - moodle-php
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - moodle-net

  moodle-php:
    image: docker-moodle-50-moodle-php:latest
    volumes:
      - /home/docker-moodle-50/moodle:/var/www/html:delegated
      - /mnt/moodledata:/var/moodledata:rw
      - /home/docker-moodle-50/php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - DB_HOST=mysql2318ae62752e.rds.ibytepluses.com
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=Moodle123#
      - REDIS_HOST=redis-mlynpi92buk1s5cya.redis.ibytepluses.com
      - REDIS_PORT=6379
      - REDIS_PASS=Moodle123
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    networks:
      - moodle-net

  moodle-cron:
    image: docker-moodle-50-moodle-cron:latest
    command: ["/usr/sbin/cron", "-f", "-L", "15"]
    volumes:
      - /home/docker-moodle-50/moodle:/var/www/html:delegated
      - /mnt/moodledata:/var/moodledata:rw
    environment:
      - DB_HOST=mysql2318ae62752e.rds.ibytepluses.com
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=Moodle123#
      - REDIS_HOST=redis-mlynpi92buk1s5cya.redis.ibytepluses.com
      - REDIS_PORT=6379
      - REDIS_PASS=Moodle123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: overlay
